services:
  client:
    build: ./PawPawsy
    container_name: client
    ports:
      - "7689:7689"
    volumes:
      - ./PawPawsy:/app/PawPawsy
      - ./PawPawsy/node_modules:/app/PawPawsy/node_modules
      # - /app/node_modules
    # env_file:
    #   - ./PawPawsy/.env
  server:
    build: ./express_api
    container_name: server
    ports:
      - "5000:5000"
    volumes:
      - ./express_api:/app/express_api
      - ./express_api/node_modules:/app/express_api/node_modules
      # - /app/node_modules
    env_file:
      - ./express_api/.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
      # - ./server/mongo-init:/docker-entrypoint-initdb.d

volumes:
  mongo-data:
